namespace Sitecore.Sharedsource
{
  public static class TextBlockUtil
  {
    /// <summary>
    /// Name of Name Value List data template field mapping tokens to substitutions.
    /// Conversion populates this field from a table in the document.
    /// </summary>
    public const string TokenMapField = "TokenMap";

    /// <summary>
    /// Name of data template field that contains the title of the text block.
    /// </summary>
    public const string TitleField = "Title";

    /// <summary>
    /// The name of the field in text blocks that can contain HTML generated by converting a Word document.
    /// </summary>
    public const string HtmlField = "Text";
  }
}